(ns ^{:deprecated "Use propagators.compiler-2.runtime"}
  graph.compiler-2-runtime
  "Deprecated compatibility facade for the compiler-2 runtime.

  Runtime implementation now lives under `propagators.compiler-2.runtime`;
  this graph namespace remains only for source compatibility."
  (:require [propagators.compiler-2.runtime :as runtime]))

(def new-session runtime/new-session)
(def ensure-session-state! runtime/ensure-session-state!)
(def record-runtime-error! runtime/record-runtime-error!)
(def default-xr-client-id runtime/default-xr-client-id)
(def compile-source! runtime/compile-source!)
(def list-cells runtime/list-cells)
(def read-cell runtime/read-cell)
(def run-runtime-cycle runtime/run-runtime-cycle)
(def commit-runtime-input runtime/commit-runtime-input)
(def commit-runtime-input! runtime/commit-runtime-input!)
(def extend-source! runtime/extend-source!)
(def semantic-trace runtime/semantic-trace)
(def semantic-expansion runtime/semantic-expansion)
(def install-semantic-trace! runtime/install-semantic-trace!)
(def read-installed-trace runtime/read-installed-trace)
(def stop-installed-trace! runtime/stop-installed-trace!)
(def schedule-trace-refreshes! runtime/schedule-trace-refreshes!)
(def refresh-trace-subscriptions! runtime/refresh-trace-subscriptions!)
(def summarize-temperature runtime/summarize-temperature)
(def drain-temperature! runtime/drain-temperature!)
(def register-tui! runtime/register-tui!)
(def commit-version! runtime/commit-version!)
(def export-instance runtime/export-instance)
(def import-instance! runtime/import-instance!)
(def append-tui-block! runtime/append-tui-block!)
(def edit-tui-block! runtime/edit-tui-block!)
(def submit-tui-block! runtime/submit-tui-block!)
(def project-tui-view runtime/project-tui-view)
(def read-tui-view runtime/read-tui-view)
(def read-agent-blocks runtime/read-agent-blocks)
(def read-agent-block runtime/read-agent-block)
(def send-agent-block! runtime/send-agent-block!)
(def unregister-tui! runtime/unregister-tui!)
(def project-xr-effects runtime/project-xr-effects)
(def read-xr-effects runtime/read-xr-effects)
(def handle-command! runtime/handle-command!)
